### ISSUE TITLE
连接Oracle数据库时报错

### ISSUE THREAD

**Issue by SamYuann** [MicrosoftDocs/powerbi-docs.zh-cn#2]
[在此处输入反馈]

我已经按照微软的官方文档安装了“64-bit ODAC 12c Release 4 (12.1.0.2.4) for Windows x64”，配置了ORACLE_HOME，本机的plsql也可以正常连接Oracle数据库，但是PowerBI连接Oracle数据库时还是报错“未安装推荐的提供程序（“Oracle.DataAccess.Client”）。可以继续使用当前提供程序，但他已被弃用，可能无法正常运行。”，为什么会出现这种情况呢？我本机安装的PowerBI版本是 2.60.5169.4101 64-bit (2018年7月)，操作系统是win10 专业版 64位。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 382f269e-2072-ec03-7c88-335cbd5df919
* Version Independent ID: 46a896f9-4707-adc3-72cd-5444a5d0f802
* Content: [连接到 Oracle 数据库 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/desktop-connect-oracle-database)
* Content Source: [powerbi-docs/desktop-connect-oracle-database.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/desktop-connect-oracle-database.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by LisandroSu** [comment]
你好，@SamYuann

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
