### ISSUE TITLE
Wrong words

### ISSUE THREAD

**Issue by Albych** [MicrosoftDocs/powerbi-docs.zh-cn#26]
https://docs.microsoft.com/zh-cn/power-bi/desktop-create-and-manage-relationships#autodetect-during-load
标题下第一段落，最后一句 “你仍可使用‘关系关系’对话框来创建或编辑关系。”
应为  你仍可使用“管理关系”对话框来创建或编辑关系。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b0390b42-0ab0-15fc-29e1-620a0ef9104c
* Version Independent ID: 44197a9d-f275-6959-8cc8-88999b740147
* Content: [在 Power BI Desktop 中创建和管理关系 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/desktop-create-and-manage-relationships#feedback)
* Content Source: [powerbi-docs/desktop-create-and-manage-relationships.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/desktop-create-and-manage-relationships.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
你好，@Albych
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Albych

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面： https://docs.microsoft.com/zh-cn/power-bi/desktop-create-and-manage-relationships

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
