### ISSUE TITLE
选择WEB方式获取数据，使用该页面的URL，导航器窗口不出现“extract data using example”选项

### ISSUE THREAD

**Issue by emily-t** [MicrosoftDocs/powerbi-docs.zh-cn#28]
选择WEB方式获取数据，使用该页面的URL，导航器窗口不出现“extract data using example”选项

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0fe95746-2616-66d1-cb63-7d62bc27c991
* Version Independent ID: e1e479f5-1fe0-3b55-f32f-153fa6197286
* Content: [通过 Power BI Desktop 中的示例从网页提取数据 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/desktop-connect-to-web-by-example#feedback)
* Content Source: [powerbi-docs/desktop-connect-to-web-by-example.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/desktop-connect-to-web-by-example.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
你好，@emily-t

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
