### ISSUE TITLE
can't show you by screenshot!!!!  fuck

### ISSUE THREAD

**Issue by samcaicn** [MicrosoftDocs/powerbi-docs.zh-cn#3]
fuck!  can't show you powerbi's bug pic

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a19d4392-fdde-d617-9091-88fdc9e97f64
* Version Independent ID: a6b1ae87-fd14-be88-fcf8-872663ccb7a4
* Content: [立刻从 Excel 工作簿变为出色的报表 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/service-from-excel-to-stunning-report#feedback)
* Content Source: [powerbi-docs/service-from-excel-to-stunning-report.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/service-from-excel-to-stunning-report.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by LisandroSu** [comment]
Hello, @samcaicn ,

Your comments are in violation of our code of conduct on https://opensource.microsoft.com/codeofconduct/. 
For this reason, we have to lock and close this issue.

Kind regards,
Microsoft DOCS International Team
