### ISSUE TITLE
SwaggerHub 不能访问

### ISSUE THREAD

**Issue by r48** [MicrosoftDocs/powerbi-docs.zh-cn#32]
希望可以提供可用API说明

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: bc6a98d6-e7d6-3d8b-5d15-b0dbf74fbd69
* Version Independent ID: 12688481-06ff-fb15-7eae-21e925492b40
* Content: [使用适用于 Power BI 报表服务器的 REST API 进行开发 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/report-server/rest-api#feedback)
* Content Source: [powerbi-docs/report-server/rest-api.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/report-server/rest-api.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srvbpigh** [comment]
Hello, @r48
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好， @r48
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team

**Comment by r48** [comment]
非常感谢答复！从文档的描述看，SwaggerHub是当前用来提供报表服务器api说明的唯一渠道，请问是否有其他渠道可用于了解服务器api说明，如果没有的话，当前文档的意义就聊胜于无。


 
---原始邮件---
发件人: "Cecilia Acevedo"<notifications@github.com>
发送时间: 2019年8月2日(星期五) 凌晨4:52
收件人: "MicrosoftDocs/powerbi-docs.zh-cn"<powerbi-docs.zh-cn@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"r48"<r48@qq.com>;
主题: Re: [MicrosoftDocs/powerbi-docs.zh-cn] SwaggerHub 不能访问 (#32)



你好， @r48
 非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 
 
请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 
 
若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 
 
非常感谢你对我们的文章作出的贡献。  
 
深深的祝福， 
 Microsoft DOCS International Team
