### ISSUE TITLE
文档提供的SwaggerHub链接不可用，请问还可以从哪里获取报表服务器可用的API清单。GitHub中只是提供个别示例。

### ISSUE THREAD

**Issue by r48** [MicrosoftDocs/powerbi-docs.zh-cn#33]
文档提供的SwaggerHub链接不可用，请问还可以从哪里获取报表服务器可用的API清单。GitHub中只是提供个别示例。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: bc6a98d6-e7d6-3d8b-5d15-b0dbf74fbd69
* Version Independent ID: 12688481-06ff-fb15-7eae-21e925492b40
* Content: [使用适用于 Power BI 报表服务器的 REST API 进行开发 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/report-server/rest-api)
* Content Source: [powerbi-docs/report-server/rest-api.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/report-server/rest-api.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srvbpigh** [comment]
Hello, @r48
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@r48
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by r48** [comment]
主要诉求是：了解powerbi的报表服务器都暴露了哪些api，以便通过外部工具操控报表服务器。

遇到的问题：在powebi报表服务器的在线文档中，只在当前文章中找到关于报表服务器api清单的说明，而当前文章只提到可以从SwaggerHub获取api清单，但文章提供的SwaggerHub链接并不可用。故至今仍不知道powebi报表服务器"提供了哪些api，这些api有哪些参数，应该如何组合参数调用这些api"。
感谢答复！如果需要我进一步提供说明，请指出要说明的地方，方便我有针对性地细化issue说明。

---原始邮件---
发件人: "Cecilia Acevedo"<notifications@github.com>
发送时间: 2019年8月6日(星期二) 凌晨2:07
收件人: "MicrosoftDocs/powerbi-docs.zh-cn"<powerbi-docs.zh-cn@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"r48"<r48@qq.com>;
主题: Re: [MicrosoftDocs/powerbi-docs.zh-cn] 文档提供的SwaggerHub链接不可用，请问还可以从哪里获取报表服务器可用的API清单。GitHub中只是提供个别示例。 (#33)



你好，@r48
 我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
 顺祝商祺！
 Microsoft DOCS 国际团队

**Comment by CeciAc** [comment]
你好，@r48

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/powerbi-docs/issues/1302 

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
