### ISSUE TITLE
筛选器侧边栏

### ISSUE THREAD

**Issue by NooWinFr** [MicrosoftDocs/powerbi-docs.zh-cn#35]
你好，文中似乎没有指出如何修改筛选器侧边栏的主题。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [在 Power BI Desktop 中使用报表主题 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/desktop-report-themes#report-theme-json-file-format)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @NooWinFr
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #1328](https://github.com/MicrosoftDocs/powerbi-docs/issues/1328) via [**ZenHub**](https://www.zenhub.com/)
