### ISSUE TITLE
在sharepoint2016中嵌入powerbi报表会一直显示“正在加载数据”，有没有大神给个解决方案噢。

### ISSUE THREAD

**Issue by cxl1989213** [MicrosoftDocs/powerbi-docs.zh-cn#36]
在sharepoint2016中嵌入powerbi报表会一直显示“正在加载数据”，有没有大神给个解决方案噢。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 4f0c4f04-7975-0f89-d5db-7b3e3a5b42f6
* Version Independent ID: b2c4c36e-c00e-ba79-8dc6-df56c696be2c
* Content: [在 SharePoint Server 中使用 iFrame 嵌入“Power BI 报表服务器”报表 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/report-server/quickstart-embed#feedback)
* Content Source: [powerbi-docs/report-server/quickstart-embed.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/report-server/quickstart-embed.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by CeciAc** [comment]
你好，@cxl1989213

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
