### ISSUE TITLE
Error on running Python script on Power BI--ErrorCode=-2147467259

### ISSUE THREAD

**Issue by linxurong** [MicrosoftDocs/powerbi-docs.zh-cn#42]
I found a error most of time when I run a python script on Power BI, how to solve this issue

DataSource.Error: ADO.NET: A problem occurred while processing your Python script. 
Here are the technical details: Process must exit before requested information can be determined.
Details:
    DataSourceKind=Python
    DataSourcePath=Python
    Message=A problem occurred while processing your Python script. 
Here are the technical details: Process must exit before requested information can be determined.
    ErrorCode=-2147467259
    ExceptionType=Microsoft.PowerBI.Scripting.Python.Exceptions.PythonUnexpectedException

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 070da3e8-5146-a2ca-9ac3-ed77621fc050
* Version Independent ID: 2dcfbb4b-3661-50bb-43b7-050aa77e710d
* Content: [在 Power BI Desktop 中运行 Python 脚本 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/desktop-python-scripts#feedback)
* Content Source: [powerbi-docs/desktop-python-scripts.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/desktop-python-scripts.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by srvbpigh** [comment]
Hello, @linxurong
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by linxurong** [comment]
Any feedback ?

**Comment by CeciAc** [comment]
Hello, @linxurong 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here -https://github.com/MicrosoftDocs/powerbi-docs/issues/1495

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
