### ISSUE TITLE
隐私级别 in desktop / dataflow / gateway

### ISSUE THREAD

**Issue by NooWinFr** [MicrosoftDocs/powerbi-docs.zh-cn#43]
隐私级别让人困惑！desktop中设置了隐私级别，dataflow中又有隐私级别。gateway里也有隐私级别。那么，他们之间如果配置有差异，是不是就不能正确使用网关了？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: eb7743c4-abb7-9c9d-6089-eca63ba9ac94
* Version Independent ID: c5bfefde-15ff-683c-5a79-e7210b8bf984
* Content: [了解 Power BI Desktop 隐私级别 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/desktop-privacy-levels#feedback)
* Content Source: [powerbi-docs/desktop-privacy-levels.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/desktop-privacy-levels.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @NooWinFr
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
