### ISSUE TITLE
推送数据集支持数据中不同变量维度的关联吗？

### ISSUE THREAD

**Issue by miya898** [MicrosoftDocs/powerbi-docs.zh-cn#48]
如题，假设想上传多个变量，还希望这些变量之间有关联，像数据库里的那样，可以吗

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a46e4476-1fc8-de9c-dc49-ffb8358d22b0
* Version Independent ID: 7af1eac8-5069-8beb-cee4-29c413f7b957
* Content: [Power BI 中的实时流式处理 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/service-real-time-streaming#feedback)
* Content Source: [powerbi-docs/service-real-time-streaming.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/service-real-time-streaming.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @miya898
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #1568](https://github.com/MicrosoftDocs/powerbi-docs/issues/1568) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@miya898

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/powerbi-docs/issues/1568。 

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
