### ISSUE TITLE
连接启用了kerberos认证的impala

### ISSUE THREAD

**Issue by SUNK2014** [MicrosoftDocs/powerbi-docs.zh-cn#51]
powerbi desktop在需要连接启用了kerberos认证的impala的情况下，我应该在哪里配置kerberos认证信息呢

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 02b27c75-1cfd-7fdd-33d8-a401fcf2989c
* Version Independent ID: 0bd5b042-8ab5-bca0-64bb-c0c59665f4d8
* Content: [在 Power BI Desktop 中连接到 Impala 数据库 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/desktop-connect-impala#feedback)
* Content Source: [powerbi-docs/desktop-connect-impala.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/desktop-connect-impala.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @SUNK2014
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@SUNK2014
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
