### ISSUE TITLE
PostgreSQL 已支持 DirectQuery

### ISSUE THREAD

**Issue by leavingme** [MicrosoftDocs/powerbi-docs.zh-cn#52]
as title

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI 数据源 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/power-bi-data-sources#feedback)
* Content Source: [powerbi-docs/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by srvbpigh** [comment]
Hello, @leavingme
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @leavingme
Thank you for your feedback and suggestion.  

The file is currently under localization process. We will release this article soon.

Many thanks for your support. 

Kind regards,

Microsoft DOCS Global Experience Team

@Alisha-Acharya
