### ISSUE TITLE
CS1061: “AuthenticationContext”未包含“AcquireToken”的定义

### ISSUE THREAD

**Issue by isKevinTrue** [MicrosoftDocs/powerbi-docs.zh-cn#53]
示例代码有误
错误	CS1061: “AuthenticationContext”未包含“AcquireToken”的定义，并且找不到可接受第一个“AuthenticationContext”类型参数的可访问扩展方法“AcquireToken”(是否缺少 using 指令或程序集引用?)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: bef3a0a2-7cc8-136e-eb8e-a80f4cade7d3
* Version Independent ID: 20093c04-76cd-9266-e2f1-96c329da93c1
* Content: [获取身份验证访问令牌 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/developer/walkthrough-push-data-get-token#feedback)
* Content Source: [powerbi-docs/developer/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/developer/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by srvbpigh** [comment]
Hello, @isKevinTrue
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@isKevinTrue 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://docs.microsoft.com/en-us/power-bi/developer/walkthrough-push-data-get-token#feedback。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team

**Comment by isKevinTrue** [comment]
@srvbpigh 但是原始文档就是错误的啊

**Comment by isKevinTrue** [comment]
@CeciAc Thank you!
