### ISSUE TITLE
感谢翻译！

### ISSUE THREAD

**Issue by Xyc0079** [MicrosoftDocs/powerbi-docs.zh-cn#55]
非常好的学习资料，感谢你们的工作！

**Comment by srvbpigh** [comment]
Hello, @Xyc0079
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
你好，@Xyc0079

非常感谢你提供反馈。很高兴我们的文档满足你的期望。  

欢迎提供宝贵的反馈，以便我们继续改进体验。  

深深的祝福，  

Microsoft DOCS International Team
