### ISSUE TITLE
如何创建聚合表

### ISSUE THREAD

**Issue by hlhxwithmj** [MicrosoftDocs/powerbi-docs.zh-cn#59]
请教下如何创建聚合表？通过"建模"模块中的"新建表"吗？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 651949b2-ae84-a7c1-d012-e41891e5931c
* Version Independent ID: bb6928af-2e51-320e-e69b-577f9bbdcd17
* Content: [在 Power BI Desktop 中使用和管理聚合 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/desktop-aggregations#feedback)
* Content Source: [powerbi-docs/desktop-aggregations.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/desktop-aggregations.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @hlhxwithmj
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #2098](https://github.com/MicrosoftDocs/powerbi-docs/issues/2098) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@hlhxwithmj 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/powerbi-docs/issues/2098。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
